# Generated by Django 4.1.5 on 2023-02-24 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_period_completeduration_period_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='newplan',
            name='is_start',
            field=models.BooleanField(default=False),
        ),
    ]
