# Generated by Django 4.1.5 on 2023-02-24 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_newplan_is_start'),
    ]

    operations = [
        migrations.RenameField(
            model_name='period',
            old_name='completeduration',
            new_name='incompleteduration',
        ),
    ]
