# Generated by Django 4.1.5 on 2023-02-24 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_completeduration_period_incompleteduration'),
    ]

    operations = [
        migrations.AddField(
            model_name='newplan',
            name='actual_start',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
