# Generated by Django 4.1.5 on 2023-02-27 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_newplan_actual_start'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newplan',
            name='actual_start',
        ),
        migrations.AddField(
            model_name='period',
            name='actual_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='period',
            name='actual_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
