# Generated by Django 4.1.5 on 2023-02-28 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_newplan_actual_start_period_actual_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newplan',
            name='clockstart_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
