# Generated by Django 4.1.5 on 2023-03-03 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_newplan_clockstart_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='period',
            name='starttime',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
