# Generated by Django 4.1.5 on 2023-03-09 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_period_starttime'),
    ]

    operations = [
        migrations.AddField(
            model_name='period',
            name='timerTravel_status',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
