# Generated by Django 4.1.5 on 2023-03-09 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_period_timertravel_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='period',
            name='timerTravel_status',
        ),
        migrations.AddField(
            model_name='newplan',
            name='timerTravel_status',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
